import ClientProvider from '@/store/Provider'
import './globals.css'
import type { Metadata } from 'next'
import Header from '@/components/Header'
import { Toaster } from 'react-hot-toast'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body >
        <ClientProvider>
          <Header/>
          {children}
          <Toaster/>
        </ClientProvider>
      </body>
    </html>
  )
}
